version: '3.9'

services:
  project.1-domain.1-svc:
    image: project.1.domain.1-svc
    networks:
      - dev-net
    container_name: project.1.domain.1-svc
    build:
      dockerfile: dockerfile
    ports:
      - "3118:3118"
      - "80:8080"
    healthcheck:
      # test: ["CMD", "bin/grpc_health_probe-linux-amd64", "-addr=localhost:3118", "||", "echo %errorlevel%"]
      test: curl --fail http://localhost:8080/health/ready || exit 1
      interval: 1s
      timeout: 3s
      start_period: 5s
      retries: 5
networks:
  dev-net:
    name: project.1-dev-net
    external: true