FROM mcr.microsoft.com/dotnet/aspnet:7.0-jammy AS base
RUN apt-get update && apt-get upgrade -y && apt-get install -y curl

WORKDIR /app
EXPOSE 8080
EXPOSE 3118

ARG GROUP_NAME=appgroup
ARG GROUP_UID=1001
ARG USER_NAME=appuser
ARG USER_UID=1001

# Create a group as system group
RUN groupadd --gid ${GROUP_UID} ${GROUP_NAME} --system\
# Create a non root user as system user belonging to that group.
  && useradd --uid $USER_UID --gid ${GROUP_UID} --system --shell /bin/sh ${USER_NAME}

USER ${USER_UID}

COPY ./publish .
ENTRYPOINT ["dotnet", "Project.1.Template.1.dll"]
