on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**/**.md'
      - 'docs/**'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '**/**.md'
      - 'docs/**'
      
env:
  MAJOR_MINOR_VERSION: 0.2

name: ci-template-dotnet

jobs:
  publish_template:
    name: "Pack template-dotnet and publish it"
    runs-on: ubuntu-latest
    steps:
    - name: Version suffix
      id: version_suffix
      run: |
        if [[ ${{ github.event_name }} == 'pull_request' ]]; then
          echo 'for pull request pipeline'
          USE=true
          OUTPUT=${GITHUB_HEAD_REF##*/}
          PATCH="-${OUTPUT}"
        else
          if [[ ${{ github.ref }} == "refs/heads/${{ github.event.repository.default_branch }}" ]]; then
            echo 'for default branch pipeline'
            USE=false
            OUTPUT=''
            PATCH=''
          else
            echo 'for feature branch pipeline'
            USE=true
            OUTPUT=${GITHUB_REF##*/}
            PATCH="-${OUTPUT}"
          fi
        fi
        echo 'use_version_suffix' $USE
        echo 'version_suffix: ' $OUTPUT
        echo "version_suffix=$OUTPUT" >> $GITHUB_OUTPUT
        echo "use_version_suffix=$USE" >> $GITHUB_OUTPUT
        echo "patch=$PATCH" >> $GITHUB_OUTPUT
    - name : Semantic version
      id: semantic_version
      run: |
        MAJOR_MINOR_PATCH_VERSION="${{ env.MAJOR_MINOR_VERSION }}.${{github.run_number}}"
        SEMANTIC_VERSION="${MAJOR_MINOR_PATCH_VERSION}${{ steps.version_suffix.outputs.patch }}"
        echo 'MAJOR_MINOR_PATCH_VERSION: ' $MAJOR_MINOR_PATCH_VERSION
        echo 'SEMANTIC_VERSION: ' $SEMANTIC_VERSION
        echo "semantic_version=$SEMANTIC_VERSION" >> $GITHUB_OUTPUT
        echo "major_minor_patch_version=$MAJOR_MINOR_PATCH_VERSION" >> $GITHUB_OUTPUT
    - name: Set dotnet parameter
      id: dotnet
      run: |
        ARGS=()
        ARGS+=("-p:VersionPrefix=${{ steps.semantic_version.outputs.major_minor_patch_version }}")
        if [[ "${{ steps.version_suffix.outputs.use_version_suffix }}" == 'true' ]]; then
          ARGS+=('--version-suffix' "${{ steps.version_suffix.outputs.version_suffix }}")
        fi
        echo 'parameters' ${ARGS[@]}
        echo "parameters=${ARGS[@]}" >> $GITHUB_OUTPUT
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 7.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
       dotnet build --no-restore -c Release ${{ steps.dotnet.outputs.parameters }}
    - name: Pack
      run: |
        dotnet pack --no-restore --no-build -c Release ${{ steps.dotnet.outputs.parameters }}
    - name: Publish
      run: dotnet nuget push **\**.nupkg --source "https://nuget.pkg.github.com/KinNeko-De" --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
    - name: Create semantic versioning git tag
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ steps.semantic_version.outputs.semantic_version }}",
            sha: context.sha
          })
